### ISSUE TITLE
Исправить алгоритм

### ISSUE THREAD

**Issue by Kasiwadzaki** [Kirill-Pyatyshev/TestTask_UnoSoft#1]
Добрый день, меня зовут Вадим, я разработчик компании UnoSoft.

На большом файле(https://github.com/PeacockTeam/new-job/releases/download/v1.0/lng-big.7z) код падает с OutOfMemoryError при ограничении памяти 1G.  
Так же небольшое пожелание, лучше всего передавать в аргументах ссылку на файл, а не его имя, получается чтобы запустить программу из  CLI надо сбилдить jar с файлом внутри иначе ничего не заработает.

**Comment by Kirill-Pyatyshev** [comment]
Доброго времени суток, извиняюсь не увидел ваш комментарий.

Изменил чтение файла, чтобы не хранить строки в памяти. Что касается аргумента я пока сделал путь до файла, что касается ссылки, в начале я должен разархивировать его?

**Comment by alexkoss** [comment]
Добрый день, Кирилл. @Kirill-Pyatyshev 
Файл можно скачать, разархивировать, положить рядом с jar-ом.
Работать - уже с разархивированным csv

**Comment by Kirill-Pyatyshev** [comment]
Здравствуйте, если поместить файл рядом с jar-ом, то можно сделать так.

**Comment by Kasiwadzaki** [comment]
@Kirill-Pyatyshev
Добрый день, результат правильный, по времени и памяти все ок. Но есть момент, в тех. задании есть условие 
```
в) Вывести полученные группы в файл в следующем формате:
```
У вас в программе не соблюдается такое и весь вывод идет в консоль, прошу доработать этот момент(соблюдая время в 30 секунд и условие по памяти)

**Comment by Kirill-Pyatyshev** [comment]
Здравствуйте, извиняюсь, как то пропустил этот пункт. Исправил недочет.
